# Generated by Django 6.0.7 on 2026-08-24 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_ai_model_workspace_ai_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='WorkspaceContextItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('context_type', models.CharField(choices=[('USER_CONTEXT', 'User Context'), ('REFERENCE', 'Reference Document'), ('INSTITUTIONAL_REFERENCE', 'Institutional Reference')], default='USER_CONTEXT', max_length=50)),
                ('source_type', models.CharField(choices=[('MANUAL_TEXT', 'Manual Text'), ('FILE_UPLOAD', 'File Upload')], default='MANUAL_TEXT', max_length=50)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='workspace_context/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='text/plain', max_length=100)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('normalized_content', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('verification_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_context_items', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_items', to='workspace.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'is_active', 'is_archived'], name='workspace_w_workspa_d97c7b_idx'), models.Index(fields=['workspace', 'context_type'], name='workspace_w_workspa_ded75f_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='workspace.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
