# Generated by Django 6.0.7 on 2026-08-25 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_workspace_system_prompt_workspacecontextitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="context_window_limit",
            field=models.IntegerField(default=4000),
        ),
        migrations.AddField(
            model_name="workspace",
            name="institutional_knowledge_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="policy_engine_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="workflow_execution_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="WorkspaceContextItemChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "context_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="workspace.workspacecontextitem",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["context_item"], name="workspace_w_context_c90a4a_idx"
                    )
                ],
                "unique_together": {("context_item", "chunk_index")},
            },
        ),
    ]
