# Generated by Django 6.0.7 on 2026-08-25 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_certificaterequest_grievanceescalation_and_more'),
        ('workspace', '0005_alter_workspacemembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('request_type', models.CharField(choices=[('GRIEVANCE', 'Grievance'), ('CERTIFICATE', 'Certificate Request'), ('MAINTENANCE', 'Maintenance Ticket'), ('LAB_BOOKING', 'Laboratory Booking'), ('GENERAL', 'General Request')], default='GENERAL', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('decision_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ESCALATED', 'Escalated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=50)),
                ('execution_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('execution_result', models.JSONField(blank=True, null=True)),
                ('execution_evidence', models.JSONField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_requests', to='workspace.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('NEW_REQUEST', 'New Request'), ('REQUEST_ESCALATED', 'Request Escalated'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_COMPLETED', 'Request Completed'), ('REQUEST_FAILED', 'Request Failed'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspace.workspace')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='task.workspacerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(default='SYSTEM', max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, default='', max_length=50)),
                ('to_status', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='task.workspacerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workspacerequest',
            index=models.Index(fields=['workspace', 'decision_status'], name='task_worksp_workspa_fea978_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacerequest',
            index=models.Index(fields=['workspace', 'requester'], name='task_worksp_workspa_af10f2_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacerequest',
            index=models.Index(fields=['workspace', 'is_archived'], name='task_worksp_workspa_6a7dda_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacerequest',
            index=models.Index(fields=['display_id'], name='task_worksp_display_5898fb_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacenotification',
            index=models.Index(fields=['workspace', 'recipient', 'is_read'], name='task_worksp_workspa_da1ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacenotification',
            index=models.Index(fields=['created_at'], name='task_worksp_created_ed3569_idx'),
        ),
        migrations.AddIndex(
            model_name='requestevent',
            index=models.Index(fields=['request', 'created_at'], name='task_reques_request_b117fb_idx'),
        ),
    ]
